language: python
python:
  - "3.6"
before_install:
install:
  - pip install -r requirements.txt
script:
  - pytest
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master